name = "cryonova"
main = "worker.js"
compatibility_date = "2026-05-03"

[[kv_namespaces]]
binding = "CRYONOVA_KV"

[vars]
GITHUB_API_URL = "https://api.github.com/repos/s4456068-hub/Cryonova/contents/Cryonova.lua?ref=main"

# Do not put GITHUB_TOKEN here.
# Add it as a secret:
# wrangler secret put GITHUB_TOKEN
